spring.application.name=payslip-generator-service

server.port=8082

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

#App info
info.app.name=Payslip Generator Service
info.app.version=1.0.0
info.app.description=Microservice for generating payslips

#API Key
api.security.key=my-secret-api-key

#Thymleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

payslip.storage.path=/tmp/payslips